version: "3.3"
services:
    frontend:
        restart: unless-stopped
        container_name: django-react-boilerplate-frontend

        build:
            context: .
            dockerfile: ./frontend/Dockerfile

        ports:
            - ${PORT:-80}:80

        environment:
            - MEDIA_ROOT=${MEDIA_ROOT}

        volumes:
            - static_volume:/app/api/django_static/
            - media_volume:${MEDIA_ROOT}

        depends_on:
            - backend

    backend:
        restart: unless-stopped
        container_name: django-react-boilerplate-backend

        build:
            context: .
            dockerfile: ./api/Dockerfile

        volumes:
            - static_volume:/app/api/django_static/
            - media_volume:${MEDIA_ROOT}

        ports:
            - 8000:8000

        depends_on:
            - db

    db:
        restart: unless-stopped
        image: postgres:15-alpine
        container_name: django-react-boilerplate-db
        expose:
            - 5432

        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_USER=postgres
            - APP_DB_NAME=${DATABASE_NAME}
            - APP_DB_USER=${DATABASE_OWNER}
            - APP_DB_PASS=${DATABASE_PASSWORD}

        volumes:
            - ./db:/docker-entrypoint-initdb.d/
            - ${DATABASE_DATA_VOLUME}:/var/lib/postgresql/data

volumes:
    static_volume: {}
    media_volume: {}
    log_volume: {}
