version: '3.1'

services:

    frontend:
        restart: unless-stopped
        container_name: django-react-boilerplate-frontend

        build:
            context: .
            dockerfile: ./frontend/Dockerfile

        ports:
            - ${PORT:-80}:80

        environment:
            - MEDIA_ROOT

        volumes:
            - static_volume:/app/api/django_static/
            - type: bind
              source: ${MEDIA_VOLUME:-$MEDIA_ROOT}
              target: ${MEDIA_ROOT}
            - type: bind
              source: ${LOG_VOLUME:-LOG_FILE_DIRECTORY}
              target: ${LOG_FILE_DIRECTORY}

        depends_on:
            - backend

    backend:
        restart: unless-stopped
        container_name: django-react-boilerplate-backend

        build:
            context: .
            dockerfile: ./api/Dockerfile

        volumes:
            - static_volume:/app/api/django_static/
            - type: bind
              source: ${MEDIA_VOLUME:-$MEDIA_ROOT}
              target: ${MEDIA_ROOT}

        ports:
            - 8000:8000
        

        depends_on:
            - db

    db:
        restart: unless-stopped
        image: postgres:10-alpine
        container_name: django-react-boilerplate-db
        expose:
            - 5432

        environment:
            - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
            - POSTGRES_USER=postgres
            - APP_DB_NAME=${DATABASE_NAME}
            - APP_DB_USER=${DATABASE_OWNER}
            - APP_DB_PASS=${DATABASE_PASSWORD}

        volumes:
            - type: bind
              source: ./db
              target: /docker-entrypoint-initdb.d/

            - type: bind
              source: ${DATABASE_DATA_VOLUME:-./db/}
              target: /var/lib/postgresql/data


volumes:
    static_volume: {}